---
# Vagrant default provider
# Default to virtualbox
# Also available: vmware_fusion, vmware_workstation
provider: "virtualbox"

# Virtual Machine name
name: "homestead"

# IP address
ip: "192.168.10.10"

# System settings
cpus: 1
memory: 2048

# Shared folders ∞
# Also think about relative paths (~)
folders:
  - guest: /home/vagrant/shared
    host: ./shared

# Nginx sites ∞
# For HHVM, set hhvm: true
sites:
  - map: homestead.app
    to: /home/vagrant/shared/laravel/public

# Databases ∞
databases:
  - homestead

# Local variables ∞
variables:
  - key: APP_ENV
    value: local

# Blackfire config
# blackfire:
#   - id: foo
#     token: bar
