---
hostname: "homestead"

ip: "192.168.10.10"
memory: 2048
cpus: 1

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ./www/default
      to: /home/vagrant/default

sites:
    - map: homestead.app
      to: /home/vagrant/default/public

databases:
    - homestead

variables:
    - key: APP_ENV
      value: local
