---
# Vagrant default provider
# Default to virtualbox
# Also available: vmware_fusion, vmware_workstation
provider: "virtualbox"

# Virtual Machine name
name: "homestead"

# IP address
ip: "192.168.10.10"

# System settings
cpus: 1
memory: 2048

# Forwarded ports ∞
ports:
  - guest: 80
    host: 8000
  - guest: 443
    host: 44300
  - guest: 3306
    host: 33060
  - guest: 5432
    host: 54320

# Shared folders ∞
# Also think about relative paths (~)
folders:
  - guest: /home/vagrant/code
    host: ./code

# Nginx sites ∞
# For HHVM, set hhvm: true
sites:
  - map: homestead.app
    to: /home/vagrant/code/laravel/public

# Databases ∞
databases:
  - homestead

# Local variables ∞
variables:
  - key: APP_ENV
    value: local
