---
hostname: "homestead"

ip: "192.168.10.10"
memory: 2048
cpus: 1

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ./www/default
      to: /home/vagrant/default
    ### another example ###
    # - map: ~/Projects/awesome
    #   to: /home/vagrant/awesome

sites:
    - map: homestead.app
      to: /home/vagrant/default/public
    ### another example ###
    # - map: awesome.app
    #   to: /home/vagrant/awesome/public

databases:
    - homestead

variables:
    - key: APP_ENV
      value: local
